apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-volume
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk: 
      fsType: ext4
      pdName: my-data-disk
  storageClassName: gcp-disk
